name: Build and Release PDF

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  sotsuron:
    uses: ./.github/workflows/build-and-release.yml
    with:
      file: sotsuron

  gaiyou:
    uses: ./.github/workflows/build-and-release.yml
    with:
      file: gaiyou
