name: Build and Release PDF

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  sotsuron:
    uses: smkwlab/latex-release-action@v1
    with:
      file: sotsuron

  gaiyou:
    uses: smkwlab/latex-release-action@v1
    with:
      file: gaiyou
