name: Build and Release PDF

on:
  pull_request_target:

permissions:
  contents: write

jobs:
  build:
    uses: smkwlab/latex-release-action@405d9e2533d9da5bdc061bda172cd406d22db287
    with:
      file: sotsuron, gaiyou
