name: Build and Release PDF

on:
  pull_request_target:

permissions:
  contents: write

jobs:
  sotsuron:
    uses: smkwlab/latex-release-action@v1
    with:
      file: sotsuron

  gaiyou:
    uses: smkwlab/latex-release-action@v1
    with:
      file: gaiyou
